### ISSUE TITLE
I get a new error when calling setBagistoVite() on an empty object. This happens when the current() function returns null, but then you still try to call setBagistoVite() before returning the result.

### ISSUE THREAD

**Issue by Lengochuy1302** [webbycrown/blog-for-bagisto#3]
I get a new error when calling setBagistoVite() on an empty object. This happens when the current() function returns null, but then you still try to call setBagistoVite() before returning the result.
When I visit the eCommerce side: http://example.com/public/blog
![image](https://github.com/webbycrown/blog-for-bagisto/assets/54675603/cfe04f7e-8dd5-4ad8-aa6a-a84858a6cf35)

Log: 
```
2024-04-08 21:02:01.878652 [NOTICE] [2407626] [T0] [14.176.199.233:59697-H3:46A3A32F8AD9A53D-8#APVH_forphones.vn:443] [STDERR] ome/gnslpcxah...')\n#8 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(125): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()\n#9 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()\n#10 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(72): Illuminate\View\Engines\PhpEngine->evaluatePath()\n#11 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(207): Illuminate\View\Engines\CompilerEngine->get()\n#12 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\View\View->getContents()\n#13 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\View\View->renderContents()\n#14 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\View\View->render()\n#15 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\Http\Response->setContent()\n#16 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\Http\Response->__construct()\n#17 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\Routing\ResponseFactory->make()\n#18 /home/gnslpcxahosting/public_html/packages/Webkul/Core/src/Exceptions/Handler.php(92): Illuminate\Routing\ResponseFactory->view()\n#19 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(535): Webkul\Core\Exceptions\Handler->Webkul\Core\Exceptions\{closure}()\n#20 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(465): Illuminate\Foundation\Exceptions\Handler->renderViaCallbacks()\n#21 /home/gnslpcxahosting/public_html..
2024-04-08 21:02:01.878638 [NOTICE] [2407626] [T0] [14.176.199.233:59697-H3:46A3A32F8AD9A53D-8#APVH_forphones.vn:443] [STDERR] Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse()\n#26 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()\n#27 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()\n#28 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()\n#29 {main}\n\nNext Illuminate\View\ViewException: Call to a member function setBagistoVite() on null (View: /home/gnslpcxahosting/public_html/packages/Webkul/Shop/src/Resources/views/components/layouts/index.blade.php) in /home/gnslpcxahosting/public_html/packages/Webkul/Theme/src/Themes.php:279\nStack trace:\n#0 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()\n#1 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(72): Illuminate\View\Engines\PhpEngine->evaluatePath()\n#2 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(207): Illuminate\View\Engines\CompilerEngine->get()\n#3 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\View\View->getContents()\n#4 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\View\View->renderContents()\n#5 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesComponents.php(103): Illuminate\View\View->render()\n#6 /home/gnslpcxahosting/public_html/storage/framework/views/cfa5845fa678e46577e3cc0792881540.php(88): Illuminate\View\Factory->renderComponent()\n#7 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): require('/h
2024-04-08 21:02:01.878625 [NOTICE] [2407626] [T0] [14.176.199.233:59697-H3:46A3A32F8AD9A53D-8#APVH_forphones.vn:443] [STDERR] luminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()\n#13 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(72): Illuminate\View\Engines\PhpEngine->evaluatePath()\n#14 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(207): Illuminate\View\Engines\CompilerEngine->get()\n#15 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\View\View->getContents()\n#16 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\View\View->renderContents()\n#17 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\View\View->render()\n#18 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\Http\Response->setContent()\n#19 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\Http\Response->__construct()\n#20 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\Routing\ResponseFactory->make()\n#21 /home/gnslpcxahosting/public_html/packages/Webkul/Core/src/Exceptions/Handler.php(92): Illuminate\Routing\ResponseFactory->view()\n#22 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(535): Webkul\Core\Exceptions\Handler->Webkul\Core\Exceptions\{closure}()\n#23 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(465): Illuminate\Foundation\Exceptions\Handler->renderViaCallbacks()\n#24 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(218): Illuminate\Foundation\Exceptions\Handler->render()\n#25 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(195): 
2024-04-08 21:02:01.878609 [NOTICE] [2407626] [T0] [14.176.199.233:59697-H3:46A3A32F8AD9A53D-8#APVH_forphones.vn:443] [STDERR] PHP Fatal error:  Uncaught Error: Call to a member function setBagistoVite() on null in /home/gnslpcxahosting/public_html/packages/Webkul/Theme/src/Themes.php:279\nStack trace:\n#0 /home/gnslpcxahosting/public_html/storage/framework/views/2b9b5bb5dde022055f246c10a6432cb5.php(47): Webkul\Theme\Themes->setBagistoVite()\n#1 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): require('/home/gnslpcxah...')\n#2 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(125): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()\n#3 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()\n#4 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(72): Illuminate\View\Engines\PhpEngine->evaluatePath()\n#5 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(207): Illuminate\View\Engines\CompilerEngine->get()\n#6 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\View\View->getContents()\n#7 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\View\View->renderContents()\n#8 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesComponents.php(103): Illuminate\View\View->render()\n#9 /home/gnslpcxahosting/public_html/storage/framework/views/cfa5845fa678e46577e3cc0792881540.php(88): Illuminate\View\Factory->renderComponent()\n#10 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): require('/home/gnslpcxah...')\n#11 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(125): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()\n#12 /home/gnslpcxahosting/public_html/vendor/laravel/framework/src/Il
```

**Comment by rohit-ghoghari** [comment]
👋 Hi @Lengochuy1302 ,

Please try setting up the complete flow by following the official Bagisto documentation.
This error will be resolved once the project is properly configured.

The issue you’re experiencing is not related to our BlogForBagisto extension, but rather to the core Bagisto setup (specifically how setBagistoVite() is called when the app context is missing).

Once your Bagisto environment is correctly set up, this error should no longer occur. ✅
